Integración Continua
====================
Yeray Darias Camacho <ydarias@gmail.com>

Independientemente de si el equipo de desarrollo sigue una metodología 
clásica en cascada o algún tipo de metodología ágil, hay un momento decisivo
que determina el éxito del proyecto. Este momento es el despliegue de la 
aplicación en los sistemas del cliente, lo que conocemos como sistema de
producción.

Generalmente este suele ser un momento muy tenso porque es muy raro que todo
funcione a la primera. Si sigues una metodología en la que predomine el 
desarrollo iterativo, en el que las funcionalidades se van entregando poco a 
poco, se minimiza ligeramente el impacto, pero sigue siendo un momento incomodo.
Se suelen producir errores porque las máquinas de desarrollo tienen 
configuraciones diferentes a las máquina de producción, el rendimiento no es 
tan bueno porque la base de datos de producción tiene una cantidad mucho mayor
de información, o cualquier otro detalle que no tuvimos en cuenta durante el
desarrollo.

Para resolver este problema aparece una nueva "filosofía" o forma de ver el
desarrollo de software denominada Integración Continua. Para muchas personas
la integración continua es tener un servidor Jenkins o Cruise Control 
construyendo nuestra aplicación continuamente. Nada más lejos de la realidad,
cuando he utilizada la palabra filosofía lo he hecho porque la Integración 
Continua es un modo de desarrollar un poco diferente al habitual, y que requiere
de una serie de buenas prácticas y la aceptación de las mismas por el equipo de
desarrollo.

Construcción automatizada y servidor de Integración Continua
------------------------------------------------------------

La primera pieza indispensable para poder llevar a cabo

[Mostrar pantalla de configuración de Jenkins de un proyecto basado en Maven]

Pruebas automatizadas
---------------------

Aunque lográramos 

Propiedad colectiva del código
------------------------------

[bibliography]
Bibliografía
------------
- [[[continuosdelivery]]] Jez Humble and David Farley 'Continuos Delivery'  
  Addison-Wesley Professional ISBN 978-0321601919
- [[[]]] Carlos Blé Jurado 'Diseño Ágil con TDD' ISBN 978-1445264714